### ISSUE TITLE
Security vulnerabilites

### ISSUE THREAD

**Issue by peterennis** [gms1/node-sqlite3-orm#41]
Possible solution in PR #40

**Comment by gms1** [comment]
yes, I would for sure have liked to have them fixed, but these vulnerable packages are still referenced from the stable release 3.9.1 of gulp; see:
```
# Run  npm install --save-dev gulp@4.0.0  to resolve 5 vulnerabilities
SEMVER WARNING: Recommended action is a potentially breaking change
```
Since gulp is only used as a build tool, consumer of this package are certainly not affected (gulp is only a devDependency)
And even if someone forks this project and would install all the devDependencies and would generate this package, there is no way for an attacker to exploit such DOF-vulnerabilities

**Comment by gms1** [comment]
pointing to related issues:
https://github.com/gulpjs/gulp/issues/1806
https://github.com/gulpjs/gulp/issues/1719

and here to show that this package is safe:
[![Known Vulnerabilities](https://snyk.io/test/github/gms1/node-sqlite3-orm/badge.svg)](https://snyk.io/test/github/gms1/node-sqlite3-orm)
