### ISSUE TITLE
Types failing?  Using @types/

### ISSUE THREAD

**Issue by drmikecrowe** [gms1/node-sqlite3-orm#72]
I'm seeing this error now.  Did something change in DefinitelyTyped?

```
node_modules/sqlite3orm/core/SqlDatabase.d.ts(25,20): error TS2709: Cannot use namespace 'Database' as a type.
node_modules/sqlite3orm/core/SqlStatement.d.ts(21,23): error TS2709: Cannot use namespace 'Statement' as a type.
```

**Comment by gms1** [comment]
no, the types didn't change since 2020-01-26
Build is fine in my environment and on Travis CI:
https://travis-ci.org/github/gms1/node-sqlite3-orm/builds/676801307
currently have no idea what's going on; Since you have already cloned the repo, is this issue reproducible after reinstalling using "npm ci"?

**Comment by drmikecrowe** [comment]
Yeah, this was something weird in my monorepo.  I got it worked out, sorry.

(great project, btw!)
